export default {
  login: "thijsBoet",
  id: 51137498,
  node_id: "MDQ6VXNlcjUxMTM3NDk4",
  avatar_url: "https://avatars0.githubusercontent.com/u/51137498?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/thijsBoet",
  html_url: "https://github.com/thijsBoet",
  followers_url: "https://api.github.com/users/thijsBoet/followers",
  following_url:
    "https://api.github.com/users/thijsBoet/following{/other_user}",
  gists_url: "https://api.github.com/users/thijsBoet/gists{/gist_id}",
  starred_url: "https://api.github.com/users/thijsBoet/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/thijsBoet/subscriptions",
  organizations_url: "https://api.github.com/users/thijsBoet/orgs",
  repos_url: "https://api.github.com/users/thijsBoet/repos",
  events_url: "https://api.github.com/users/thijsBoet/events{/privacy}",
  received_events_url: "https://api.github.com/users/thijsBoet/received_events",
  type: "User",
  site_admin: false,
  name: "Thijs Boet",
  company: null,
  blog: "jsdev.nl",
  location: "Rotterdam",
  email: null,
  hireable: true,
  bio:
    "I have been developing websites since the early 2000's. These days using ES6 and frameworks like React. ",
  twitter_username: null,
  public_repos: 60,
  public_gists: 0,
  followers: 0,
  following: 2,
  created_at: "2019-05-28T20:52:29Z",
  updated_at: "2020-10-06T14:54:24Z",
};